### ISSUE TITLE
Forget to put slash symbols

### ISSUE THREAD

**Issue by Gutei** [irfanpule/django-form-surveys#1]
did you forget to put slash symbols? :)

![image](https://user-images.githubusercontent.com/34201314/158136873-7fa281a0-079c-40cc-880a-7f1ffeda7094.png)

**Comment by irfanpule** [comment]
Thank for your report, maybe I wrote the wrong documentation when importing url. You must add a slash symbol at the end of the word in the url.
please you import url like this
```
urlpatterns = [
    path('admin/', admin.site.urls),
    .....
    path('surveys/', include('djf_surveys.urls'))
]
```
