### ISSUE TITLE
BUG: Download Report

### ISSUE THREAD

**Issue by alinnural** [irfanpule/django-form-surveys#23]
Halo,

Sepertinya saya menemukan bug pada hasil report atau download respon. Jadi ada beberapa jawaban yang header nya tidak sesuai, seperti gambar berikut pada baris ketiga dari bawah..

<img width="1225" alt="Screen Shot 2022-07-22 at 11 26 12" src="https://user-images.githubusercontent.com/10736456/180362373-69acce85-2622-4a3f-bc02-f2ab68ed018a.png">

**Comment by irfanpule** [comment]
Hai @alinnural terima kasih untuk laporannya. Agak aneh knp ini bisa terjadi, saya akan coba cek kembali kode pada fungsi download report. Oh ya, apakah form ini pernah mengalami perubahan type field? Misal yg sebelumnya type field adalah number, lalu diubah ke text?

Jika iya kemungkinan jawaban yg berbeda itu adalah answer value dari question field type yg sebelumnya

**Comment by alinnural** [comment]
<img width="1098" alt="Screen Shot 2022-07-22 at 18 34 59" src="https://user-images.githubusercontent.com/10736456/180431149-2f3c2297-1d7f-4c54-8611-4dcf9034bb23.png">

kalau dilihat dari detail survey nya, kasus yang report nya tidak sesuai label juga tidak berurut seperti response yang lainnya.. Sepertinya bisa terjadi karena ini ya?

**Comment by irfanpule** [comment]
iya menurut saya ini ada 1 survey, kemudian perubahan fieldnya major banget.
