### ISSUE TITLE
Update string download response

### ISSUE THREAD

**Issue by alinnural** [irfanpule/django-form-surveys#24]
Halo,

Saat ini jika download response maka untuk jawaban yang tipenya choices akan menampilkan key dari pilihannya.
Setelah di telusuri sepertinya di fungsi download masih menggunakan `answer.value` sehingga masih mengambil real value, sedangkan di detail sudah menggunakan `answer.get_value` untuk menyesuaikan dengan jenis tipe datanya..

**Comment by irfanpule** [comment]
Hai @alinnural terima kasih laporannya. Akan segera di perbaiki
