### ISSUE TITLE
`Key` field on `questions`

### ISSUE THREAD

**Issue by alinnural** [irfanpule/django-form-surveys#27]
Halo,

Saya ada kebutuhan untuk mengambil jawaban dari pertanyaan tertentu. Tapi ternyata mendapat kesulitan karena pada pertanyaan tidak ada identifier yang unique yang bisa digunakan untuk langsung menunjuk ke pertanyaan pada survey tertentu.

Apa bisa ditambahkan satu field `key` pada model `questions`, sehingga untuk kasus diatas saya bisa mengambil data yang diinginkan menggunakan key..

Data Model nya mungkin bisa seperti berikut:
`key = models.CharField(unique=True, blank=True, null=True)`

Terima Kasih..

**Comment by irfanpule** [comment]
Terima kasih @alinnural untuk masukkannya. Untuk kasus ini apakah bisa bantu untuk dibuatkan Merge Request nya? 

Karena @alinnural yg lebih tahu pasti kasusnya dan penggunaannya.

**Comment by irfanpule** [comment]
https://github.com/irfanpule/django-form-surveys/releases/tag/v1.6.4

sudah saya rilis ke pypi untuk pembaruan ini di versi 1.6.4
