### ISSUE TITLE
Emojis in text responses generate errors

### ISSUE THREAD

**Issue by terencecollins** [irfanpule/django-form-surveys#31]
An emoji in the response for a text field generates an error
<img width="336" alt="Screen Shot 2022-09-21 at 10 06 21 AM" src="https://user-images.githubusercontent.com/1354778/191526218-830558e2-3ec8-4784-ab4c-7c23c0bfa078.png">

**Comment by irfanpule** [comment]
thanks for the report. I didn't really think it supported emojis. maybe in the next feature.

**Comment by irfanpule** [comment]
Hi @terencecollins, 

I have try input emoji use iphone and android, it's worked. I have’t founded your error.
![EDC40754-DA4C-404A-8E9B-0EE6784F6728](https://user-images.githubusercontent.com/11069520/197442349-0e0ba2dc-a521-436d-969e-b073ce61195e.jpeg)

I can you explain more about this issue? How do you input emoji in a textfield?

**Comment by irfanpule** [comment]
Hi @terencecollins 

acctually I am developing use sqlite. I look you using mysql, maybe this can help you. https://stackoverflow.com/questions/41311547/python3django1-10mysqlclient1-3-9-cannot-save-emoji-characters

Thank you.
