### ISSUE TITLE
Got Error on share link when user didn't have answer !!!

### ISSUE THREAD

**Issue by Gutei** [irfanpule/django-form-surveys#39]
error msg: ```surveys.views.share_link didn't return an HttpResponse object. It returned None instead.```

![image](https://user-images.githubusercontent.com/34201314/209486127-826c13ef-27d5-4af7-9503-0491be88becf.png)

I think you forget to return method when the user didn't have answer

**Comment by irfanpule** [comment]
Hi @Gutei thank for the report, I will fix it
