### ISSUE TITLE
Error migration

### ISSUE THREAD

**Issue by Gutei** [irfanpule/django-form-surveys#40]
I already have DB with the previous version `DJF 1.6.5` and I got an error when running the migration of file `0010_model_translation` ...

msg : 
```
django.db.utils.IntegrityError: duplicate key value violates unique constraint "djf_surveys_question_key_key"
DETAIL:  Key (key)=() already exists.
```

can you help with that !!

**Comment by irfanpule** [comment]
Hi @Gutei I think error message show because on model `unique=True, default=""`. if you have two value empty string, django will give error `"duplicate key value"`.

To solve this problem, I will revert the model to `unique=True, null=True, blank=True` as used in `version 1.6.5`
