### ISSUE TITLE
Forget to remove migration

### ISSUE THREAD

**Issue by Gutei** [irfanpule/django-form-surveys#44]
pls, revert migration too. I can migrate cause it is because of issue #40,  file migration `0011_alter_question_key.py` dependencies on `0010_model_translation `. I think you need migration to file 0009, delete the 0010 migration file and make migration against to generate new file migration

**Comment by irfanpule** [comment]
Sorry I forgot that migrations are run sequentially. So the solution of changing the options in the model has no impact on your case.

I think you have to manually check the contents of the key field, are there any duplicates?

more than one empty string or more than one null may be considered a duplicate in the unique option

**Comment by irfanpule** [comment]
Hi @Gutei, is there any update for this problem?

**Comment by irfanpule** [comment]
Sorry I want close this issue. Feel free to reopen
