### ISSUE TITLE
Languages problem

### ISSUE THREAD

**Issue by GeekHamza1** [irfanpule/django-form-surveys#51]
hey bro !  i   appreciate your work in   the project
i just have question about Languages , i uncommented LANGUAGE_CODE = "fr"
but i still can see english in the project
so how i can use  the local folder transalation ?!

**Comment by irfanpule** [comment]
Hello @GeekHamza1

If you look at this https://github.com/irfanpule/django-form-surveys/tree/master/djf_surveys/locale, the only available locales are `en` and `fr`. If you remove `LANGUAGE_CODE = "fr"` it will revert to default language is `en`.

I'd like you to contribute adding your local language as this is your local language way of working on this project.

**Comment by GeekHamza1** [comment]
Hey i  want fr language  i activated LANGUAGE_CODE = "fr"
But it look like only fr language  activated in the Admin panel , i still can see english in rendred html pages ...

Its look like the fr local language  files  not activated

**Comment by irfanpule** [comment]
Oh I see. I Will check it

**Comment by irfanpule** [comment]
Hi @GeekHamza1 

After checking I thought there was no problem. Make sure you have reloaded or restarted the server.

Below is a screenshot from my development branch
<img width="1176" alt="Screenshot 2023-05-02 at 03 00 07" src="https://user-images.githubusercontent.com/11069520/235521496-ca0fdcad-36df-407d-b36c-72bfd5148c0a.png">


Next is a screenshot of the project that has installed django-form-surveys==1.7.1 via pip
<img width="1157" alt="Screenshot 2023-05-02 at 03 00 50" src="https://user-images.githubusercontent.com/11069520/235521806-8ae0636e-cd6e-408d-b014-49f6090bb102.png">

**Comment by irfanpule** [comment]
Hi @GeekHamza1 

Sorry after deep checking there are some translations not working. I don't know what the cause is yet. If you know, feel free to let us know or make a Pull Request. Thank You

**Comment by GeekHamza1** [comment]
bro i m working on debuging the problem , but its look like in your screenshot you can access translation in login.html and its working  , it seems like you have translate urlpatterns allowed ?

**Comment by GeekHamza1** [comment]
pull Request sent
