### ISSUE TITLE
editing

### ISSUE THREAD

**Issue by GeekHamza1** [irfanpule/django-form-surveys#56]
bro i need help ! i want edit in the djf_surveys app migrations and templates ... its look like ineed to edit INSIDE site-packages ...please guide me 
thanks

**Comment by irfanpule** [comment]
Hi @GeekHamza1 ,

What changes would you like to make to migration? Basically, developing the djf_surveys is the same as the django app. If you want changes outside the djf_survey development path. Please`fork` first, then follow these steps:
- clone project
- symlink app to `demo`
- `ln -s [path_project_djf_survey] [path_demo_djf_survey]`
- create env development
- active env
- enter directory demo, `cd demo`
- now, you can access all command `manage.py` and edit all code.

**Comment by GeekHamza1** [comment]
after following these steps i will be able to add new migrations in  djf_survey ?

**Comment by irfanpule** [comment]
It's same with you dev project with django.
- `edit model`
- run `python manage.py makemigrations`

**Comment by GeekHamza1** [comment]
I tried but it does not detect migrations  ..

Also for html text i should  update html  text located in site-package/djs_survey/templates ..
Can i move the djs_survey from site-packages to my project app ?

**Comment by irfanpule** [comment]
Hi @GeekHamza1 

It's not recommended to edit from the `site-package`. If you want modify it project stand alone, I think you just copy folder `djf_surveys` then including on your project. Or you can `inherited class` to modify template or adding `context`.

example:
```python
from djf_surveys.views import SurveyListView


class YourClassModifyListView(SurveyListView):
    template = 'your_template_dir/template.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['other_key'] = 'other_value'
        return context
```

**Comment by GeekHamza1** [comment]
i copyed the djf_surveys  to my project folder  and added it to setting , but  migrations not detected
