### ISSUE TITLE
Database data automatically deletes after a while. 

### ISSUE THREAD

**Issue by otuozeAhmed** [irfanpule/django-form-surveys#63]
I've cloned the project and have customized it to suit my forms data and survey. Migration and everything works fine, then I populated the database (SQLite) with Questions and Surveys.
This is where the issue comes up. After a while after I've loaded data into the database, upon loading the app I notice that all data populated have been deleted and everything looks empty as if I've never populated the database.

Kindly suggest any idea where this problem might be coming from. It's the first time I'm encountering such problem. It looks very strange to me. Do you have any automated script that wipes the database over time?

**Comment by irfanpule** [comment]
Hi @otuozeAhmed 

Thank for your report.
In this package not have automation script to wipes database.

Maybe there’s impact from other packages. Can you explain how did you installed it? Via pip or git clone?

**Comment by otuozeAhmed** [comment]
Hi Irfan, I downloaded through clone.
However I've seen what caused the issue. I switched between databases from legacy to Sqlite3 subsequently and have migrations not in order while switching them. Thanks for your fast response.
The codebase works really well now.
