### ISSUE TITLE
Datefield and large surveys

### ISSUE THREAD

**Issue by MartinK84** [irfanpule/django-form-surveys#74]
There is a gray/blue line across the page whenever using a DateField question in a survey that extends across the page vertically. 

I tried to debug it and find the source and it appears to be coming from a div right below the input field of the date picker component. I tried to go through the templates but could not find the div anywhere, so I assume it's coming from Tailwind. Since I'm not a css/js developer I unfortunately failed to investigate this further. 

![image](https://github.com/irfanpule/django-form-surveys/assets/50527612/66b3f12e-d9bb-4550-b3be-5f59eec91276)

![image](https://github.com/irfanpule/django-form-surveys/assets/50527612/39cd71f8-76d8-4ee0-96ac-2f06ebb19450)

**Comment by irfanpule** [comment]
Thank for your report. I will try resolve this
