### ISSUE TITLE
Wrap Text Details

### ISSUE THREAD

**Issue by alinnural** [irfanpule/django-form-surveys#85]
Halo pak, kami menemukan sedikit temuan di halaman details survey, teks yang diinputkan jika tidak memiliki spasi maka akan melewati card seharusnya, berikut terlampir contohnya..

![image-2](https://github.com/irfanpule/django-form-surveys/assets/10736456/a8106342-0a76-4805-981a-f061fb3d7108)

**Comment by irfanpule** [comment]
halo @alinnural 

Terima kasih untuk laporannya ya. Akan saya perbaiki.
